#! /bin/bash

#########################	Main function	###########################
function ShowMenu
{
	clear
	choix = 0
	rep = 1
	while [ $choix -ne 1 -a $choix -ne 2 -a $choix -ne 3 -a $choix -ne 4 -a $choix -ne 5 -a $choix -ne 6  ]
	do
		echo " "
		echo "    ***************************************************************"
		echo "    *                	       Users Manager 						*"
		echo "    ***************************************************************"
		echo "    *           1- Create Single User        				        *"
		echo "    *           2- Create Multiple Users 						    *"
		echo "    *           3- Delete Users 								    *"
		echo "    *           4- Show Users 				                    *"
		echo "    *           5- Manage Passwords 				                *"
		echo "    *           6- Return                                         *"
		echo "    ***************************************************************"
		echo " "
		echo -n "Choice : "
		read choix
	done
	case $choix in
		"1") AddUser;;
"2") AddUsers;;
"3") DeleteUser;;
"4") ./utilisateurs/ShowUsers;;
"5") ./utilisateurs/ManageUsers;;
"6")./ShowMenu;;
*) clear
echo "Incorrect input"
sleep 5
ShowMenu
;;
esac 
}



#########################	Sub-functions	###########################

# Verify if user exists
function UserExists
{
	a=` wc -l /etc/passwd | cut -d " " -f 1`
	echo "" > usr
	for i in `seq 1 "$a"`;
	do
		sed -n "$i"p /etc/passwd | cut -d : -f 1 >> usr 
	done
	exists=`grep -wc "$1" usr`
	if [ $exists -gt 0 ]; then
		return 0
	else return 1
	fi
}

# Show Groups
function ListGroups
{
	n=`wc -l /etc/group | cut -d " " -f 1`
	for i in `seq 1 "$n"`;
	do 
	gid=`sed -n "$i"p /etc/group | cut -d : -f 3`
	if [ "$gid" -ge 500 ] || [ "$gid" -eq 0 ]; then
		sed -n "$i"p /etc/group | cut -d : -f 1
	fi
done
}

# Add Single User

# Add Multiple Users

# Delete Users
