#! /bin/bash

#########################	Main function	###########################
function ShowMenu
{
	clear
	choice = 0
	rep = 1
	
	while [ $choice -ne 1 -a $choice -ne 2 -a $choice -ne 3 -a $choice -ne 4 -a $choice -ne 5 -a $choice -ne 6  ]
	do
		echo " "
		echo "    ***************************************************************"
		echo "    * 						Users Manager 						*"
		echo "    ***************************************************************"
		echo "    * 		1- Create Single User 								*"
		echo "    * 		2- Create Multiple Users 							*"
		echo "    * 		3- Delete Users 									*"
		echo "    * 		4- Show Users 										*"
		echo "    * 		5- Manage Passwords 								*"
		echo "    * 		6- Return 											*"
		echo "    ***************************************************************"
		echo " "
		echo -n "Choose an option : "
		read choice
	done
	
	case $choice in
		"1") AddUser;;
		"2") AddUsers;;
		"3") DeleteUser;;
		"4") ./ShowUsers;;
		"5") ./ManageUsers;;
		"6") ./ShowMenu;;
	*)
	
	clear
	echo "Incorrect input"
	sleep 5
	ShowMenu;;

	esac 
}



#########################	Sub-functions	###########################

# Verify if user exists
function UserExists
{
	a=` wc -l /etc/passwd | cut -d " " -f 1`
	echo "" > usr
	for i in `seq 1 "$a"`;
	do
		sed -n "$i"p /etc/passwd | cut -d : -f 1 >> usr 
	done
	exists=`grep -wc "$1" usr`
	if [ $exists -gt 0 ]; then
		return 0
	else return 1
	fi
}

# Show Groups
function ListGroups
{
	n=`wc -l /etc/group | cut -d " " -f 1`
	for i in `seq 1 "$n"`;
	do 
	gid=`sed -n "$i"p /etc/group | cut -d : -f 3`
	if [ "$gid" -ge 500 ] || [ "$gid" -eq 0 ]; then
		sed -n "$i"p /etc/group | cut -d : -f 1
	fi
done
}

# Add Single User
function AddUser
{
	clear
	echo "" > usr
	login=""
	nbre=0
	while [ -z $login ] || [ $nbre = 0 ]
	do
		clear
		echo " "
		read -p "Login : " login
		s=${login:0:1}
		echo "$s" > usr
		nbre=`grep -c "^[a-zA-Z]" usr`
	done 
	UserExists "$login" 
	if [ "$?" -eq 0 ]; then 
		echo "User exists. Please try with another name !!"
		sleep 2
		AddUser
	else
		ListGroups
		read -p " Choose Group : " group
		read -s -p "Password :" password
		useradd -p "$password" -g "$group" "$login" >> /dev/null 2<&1
		operation=$?
		echo "$operation"
		if [ "$operation" -eq 0 ]; then 
			echo "User was added successefully !!"
			sleep 2
			ShowMenu
		else echo "An Error was occured !!"
			sleep 2
			ShowMenu
		fi
	fi
}

# Add Multiple Users

# Delete Users
